//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : CalibrationPair.h
//  @ Date : 30/09/2012
//  @ Author : 
//
//


#if !defined(_CALIBRATIONPAIR_H)
#define _CALIBRATIONPAIR_H

#include "EyeData.h"
#include "ScreenData.h"
#include "ScreenPoint.h"

class CalibrationPair {
public:
	EyeData eye;
	ScreenData screen;
	ScreenPoint screenPoint;

    CalibrationPair();
    CalibrationPair(EyeData e, ScreenData s, ScreenPoint p);
};

#endif  //_CALIBRATIONPAIR_H
