//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : CalibrationSequence.h
//  @ Date : 30/09/2012
//  @ Author : 
//
//


#if !defined(_CALIBRATIONSEQUENCE_H)
#define _CALIBRATIONSEQUENCE_H

#include <vector>
#include "opencv2/core/core.hpp"
#include "ScreenPoint.h"
#include "CalibrationPair.h"

class CalibrationSequence {
public:
    CalibrationSequence();
    CalibrationSequence(std::vector<CalibrationPair> calpairs);
    std::vector<CalibrationPair> pairs;
    void addPair(CalibrationPair calPair);
    std::vector<CalibrationPair> getPairs(ScreenPoint filter);
};

#endif  //_CALIBRATIONSEQUENCE_H
