//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : CalibrationSequence.cpp
//  @ Date : 30/09/2012
//  @ Author : 
//
//

#include "CalibrationSequence.h"

using namespace std;

CalibrationSequence::CalibrationSequence() {}

CalibrationSequence::CalibrationSequence(std::vector<CalibrationPair> calpairs):
    pairs(calpairs)
{

}

void CalibrationSequence::addPair(CalibrationPair calPair) {
    pairs.push_back(calPair);
}

vector<CalibrationPair> CalibrationSequence::getPairs(ScreenPoint filter) {

}

