//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : EyeData.h
//  @ Date : 30/09/2012
//  @ Author : 
//
//


#if !defined(_EYEDATA_H)
#define _EYEDATA_H

#include <cmath>
#include "opencv2/core/core.hpp"

enum FixedReference {EYE_LEFT_CORNER,
                     EYE_RIGHT_CORNER,
                     WINDOW_LEFT_CORNER,
                     WINDOW_RIGHT_CORNER,
                     IMAGE_LEFT_CORNER};

class EyeData {
private:
    void normalizeData();
    FixedReference referential;
public:
    EyeData();
    EyeData(cv::Rect win, cv::Point2f lc, cv::Point2f rc, cv::Point2f i);
    EyeData(cv::Rect win, cv::Point2f lc, cv::Point2f rc, cv::Point2f i, FixedReference ref);

    cv::Rect window;
    cv::Point2f leftCorner;
    cv::Point2f rightCorner;
    cv::Point2f iris;
    cv::Point2f getLeftCornerPosition();
    cv::Point2f getRightCornerPosition();
    cv::Point2f getIrisPosition();
    double processingTime;
    double getXRef();
    double getYRef();
};

#endif  //_EYEDATA_H
