//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : LeastSquaresSolver.h
//  @ Date : 30/09/2012
//  @ Author : 
//
//


#if !defined(_LEASTSQUARESSOLVER_H)
#define _LEASTSQUARESSOLVER_H

#include "opencv2/core/core.hpp"
#include "CalibrationPair.h"
#include <iostream>

class LeastSquaresSolver {
private:
    int polyDegree;
    int sampleSize;
    cv::Mat setUpLinearSystem(const cv::Mat &xSums, const cv::Mat &ySums);
    void computeSums(const cv::Mat &xbase, const cv::Mat &ybase, cv::Mat &sigmaX, cv::Mat &sigmaY);
public:
    LeastSquaresSolver();
    LeastSquaresSolver(int size, int degree);
    cv::Mat solve(std::vector<CalibrationPair> *data);
};

#endif  //_LEASTSQUARESSOLVER_H
