//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : ScreenPoint.h
//  @ Date : 30/09/2012
//  @ Author : 
//
//


#if !defined(_SCREENPOINT_H)
#define _SCREENPOINT_H


enum ScreenPoint {
    SCREEN_POINT_NONE,
    SCREEN_POINT_LEFT_UPPER,
    SCREEN_POINT_CENTER_UPPER,
    SCREEN_POINT_RIGHT_UPPER,
    SCREEN_POINT_LEFT_MIDDLE,
    SCREEN_POINT_CENTER_MIDDLE,
    SCREEN_POINT_RIGHT_MIDDLE,
    SCREEN_POINT_LEFT_LOWER,
    SCREEN_POINT_CENTER_LOWER,
    SCREEN_POINT_RIGHT_LOWER
};

#endif  //_SCREENPOINT_H
