//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : ScreenData.h
//  @ Date : 30/09/2012
//  @ Author : 
//
//


#if !defined(_SCREENDATA_H)
#define _SCREENDATA_H

#include "opencv2/core/core.hpp"

class ScreenData {
public:
	int x;
	int y;

    double detectionTime;  // tempo em segundos gasto para detectar o olho
    double estimationTime; // tempo em segundos gasto para estimar o POG

    ScreenData();
    ScreenData(cv::Point coord);

private:
};

#endif  //_SCREENDATA_H
