//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : ScreenData.cpp
//  @ Date : 30/09/2012
//  @ Author : 
//
//


#include "ScreenData.h"

ScreenData::ScreenData() {}

ScreenData::ScreenData(cv::Point coord) :
    x(coord.x),
    y(coord.y)
{
}

