//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : GazeEstimator.cpp
//  @ Date : 30/09/2012
//  @ Author : 
//
//


#include "GazeEstimator.h"
#include "CalibrationSequence.h"
#include "ScreenData.h"
#include "EyeData.h"

void GazeEstimator::calibrate(CalibrationSequence sequence) {

}

ScreenData GazeEstimator::estimate(EyeData input) {

}

