//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : GazeEstimator.h
//  @ Date : 30/09/2012
//  @ Author : 
//
//


#if !defined(_GAZEESTIMATOR_H)
#define _GAZEESTIMATOR_H

#include "CalibrationSequence.h"
#include "ScreenData.h"
#include "EyeData.h"

class GazeEstimator {
public:
	void calibrate(CalibrationSequence sequence);
	ScreenData estimate(EyeData input);
};

#endif  //_GAZEESTIMATOR_H
