//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : LeastSquaresSolver.h
//  @ Date : 30/09/2012
//  @ Author : 
//
//


#if !defined(_LEASTSQUARESSOLVER_H)
#define _LEASTSQUARESSOLVER_H


class LeastSquaresSolver {
};

#endif  //_LEASTSQUARESSOLVER_H
