//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : LinearSolver.h
//  @ Date : 30/09/2012
//  @ Author : 
//
//


#if !defined(_LINEARSOLVER_H)
#define _LINEARSOLVER_H


class LinearSolver {
};

#endif  //_LINEARSOLVER_H
